<?php

    return[
        
        [
            'name' => 'Francesco',
            'surname'=> 'Mazilu',
            'email' => 'Fmazilu90@gmail.com',
            'password' => 'root345',
            'img' => 'https://www.thomann.de/blog/wp-content/uploads/2017/01/10-conseils-pour-devenir-musicien-pro.jpg',
            'region' => 'Calabria',
            'phone' => '3381466233',
            'cachet' => '340',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',


        ],
        [
            'name' => 'Federico',
            'surname'=> 'Zubini',
            'email' => 'zubiFede@gmail.com',
            'password' => 'ciao',
            'img' => 'https://upload.wikimedia.org/wikipedia/commons/9/91/Guy_Pratt_On_An_Island_Tour_Cropped.png',
            'region' => 'umbria',
            'phone' => '3381245786',
            'cachet' => '270',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Paola',
            'surname'=> 'Ferretti',
            'email' => 'PaolaF@yahoo.com',
            'password' => 'prova',
            'img' => 'https://www.clinicadellatimidezza.it/wp-content/uploads/2015/09/Ansia-da-prestazione-del-musicista.png',
            'region' => 'Lazio',
            'phone' => '3336857159',
            'cachet' => '550',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Matteo',
            'surname'=> 'De pietro',
            'email' => 'MDP92@libero.it',
            'password' => 'password',
            'img' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvX91rajtG6lE--8I0sp2_ULo9vtjtrwDGlg&usqp=CAU',
            'region' => 'Lazio',
            'phone' => '3384567789',
            'cachet' => '200',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'i grandi',
            'surname'=> 'suonatori',
            'email' => 'iGrandiSuonatori@gmail.com',
            'password' => 'grandissimi',
            'img' => 'https://media.istockphoto.com/id/1308631663/it/foto/rock-band-che-si-esibisce-con-chitarrista-femminile-batterista-e-cantante-maschile.jpg?s=612x612&w=0&k=20&c=XtGQFbGlsojdOuOU68kF9CNJ9fnHwG21oOdm6AKqY8I=',
            'region' => 'Puglia',
            'phone' => '3475974851',
            'cachet' => '550',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Enrico',
            'surname'=> 'De santis',
            'email' => 'enricoDS@gmail.com',
            'password' => 'criptata',
            'img' => 'https://www.thomann.de/blog/wp-content/uploads/2017/01/10-conseils-pour-devenir-musicien-pro.jpg',
            'region' => 'Molise',
            'phone' => '3331465964',
            'cachet' => '280',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Luca',
            'surname'=> 'Calva',
            'email' => 'calvaLuca@yahoo.com',
            'password' => 'root123',
            'img' => 'https://www.thomann.de/blog/wp-content/uploads/2017/01/10-conseils-pour-devenir-musicien-pro.jpg',
            'region' => 'Lazio',
            'phone' => '3384567789',
            'cachet' => '200',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Elisa',
            'surname'=> 'Couto',
            'email' => 'coutoElisa@gmail.com',
            'password' => 'prova123',
            'img' => 'https://img.freepik.com/premium-photo/pianist-musician-piano-music-playing-musical-instrument-grand-piano-with-woman-performer_104603-2849.jpg',
            'region' => 'Liguria',
            'phone' => '3381426759',
            'cachet' => '320',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'La band',
            'surname'=> 'Pazza',
            'email' => 'laBandPazza@gmail.com',
            'password' => 'pazzissimi',
            'img' => 'https://media.istockphoto.com/id/496120274/it/foto/rock-band-esecuzione-in-uno-studio.jpg?s=612x612&w=0&k=20&c=RUH-ChyL6jEeJlUrpXzAWskINSJi0E0Vg_LiNw0Ur6E=',
            'region' => 'Campania',
            'phone' => '3383255485',
            'cachet' => '420',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Francesca',
            'surname'=> 'Romiti',
            'email' => 'Fromiti97@gmail.com',
            'password' => 'psw123',
            'img' => 'https://www.ondamusicale.it/wp-content/uploads/2020/08/bonnie-raitt.jpg',
            'region' => 'Emilia Romagna',
            'phone' => '3385744816',
            'cachet' => '150',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ]
    ]
?>