<?php

    return[
        
        [
            'name' => 'Francesco',
            'surname'=> 'Mazilu',
            'email' => 'Fmazilu90@gmail.com',
            'password' => 'root345',
            'img' => 'https://www.thomann.de/blog/wp-content/uploads/2017/01/10-conseils-pour-devenir-musicien-pro.jpg',
            'region' => 'Calabria',
            'phone' => '3381466233',
            'cachet' => '340',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',


        ],
        [
            'name' => 'Federico',
            'surname'=> 'Zubini',
            'email' => 'zubiFede@gmail.com',
            'password' => 'ciao',
            'img' => 'https://upload.wikimedia.org/wikipedia/commons/9/91/Guy_Pratt_On_An_Island_Tour_Cropped.png',
            'region' => 'umbria',
            'phone' => '3381245786',
            'cachet' => '270',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Paola',
            'surname'=> 'Ferretti',
            'email' => 'PaolaF@yahoo.com',
            'password' => 'prova',
            'img' => 'https://www.clinicadellatimidezza.it/wp-content/uploads/2015/09/Ansia-da-prestazione-del-musicista.png',
            'region' => 'Lazio',
            'phone' => '3336857159',
            'cachet' => '550',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Matteo',
            'surname'=> 'De pietro',
            'email' => 'MDP92@libero.it',
            'password' => 'password',
            'img' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvX91rajtG6lE--8I0sp2_ULo9vtjtrwDGlg&usqp=CAU',
            'region' => 'Lazio',
            'phone' => '3384567789',
            'cachet' => '200',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'i grandi',
            'surname'=> 'suonatori',
            'email' => 'iGrandiSuonatori@gmail.com',
            'password' => 'grandissimi',
            'img' => 'https://media.istockphoto.com/id/1308631663/it/foto/rock-band-che-si-esibisce-con-chitarrista-femminile-batterista-e-cantante-maschile.jpg?s=612x612&w=0&k=20&c=XtGQFbGlsojdOuOU68kF9CNJ9fnHwG21oOdm6AKqY8I=',
            'region' => 'Puglia',
            'phone' => '3475974851',
            'cachet' => '550',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Enrico',
            'surname'=> 'De santis',
            'email' => 'enricoDS@gmail.com',
            'password' => 'criptata',
            'img' => 'https://www.thomann.de/blog/wp-content/uploads/2017/01/10-conseils-pour-devenir-musicien-pro.jpg',
            'region' => 'Molise',
            'phone' => '3331465964',
            'cachet' => '280',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Luca',
            'surname'=> 'Calva',
            'email' => 'calvaLuca@yahoo.com',
            'password' => 'root123',
            'img' => 'https://www.thomann.de/blog/wp-content/uploads/2017/01/10-conseils-pour-devenir-musicien-pro.jpg',
            'region' => 'Lazio',
            'phone' => '3384567789',
            'cachet' => '200',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'John',
            'surname'=> 'Doe',
            'email' => 'johndoe@example.com',
            'password' =>'test123',
            'img' => 'https://example.com/images/john.jpg',
            'region' => 'Puglia',
            'phone' => '1234567890',
            'cachet' => '1200',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius veniam inventore numquam quia!'
        ],
        [
            'name' => 'Laura',
            'surname'=> 'Smith',
            'email' => 'lsmith@example.com',
            'password' =>'securepass',
            'img' => 'https://example.com/images/laura.jpg',
            'region' => 'Sicilia',
            'phone' => '9876543210',
            'cachet' => '800',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae nihil cum officiis omnis tempore eveniet!'
        ],
        [
            'name' => 'Michele',
            'surname'=> 'Ricci',
            'email' => 'mricci@example.com',
            'password' =>'michele123',
            'img' => 'https://example.com/images/michele.jpg',
            'region' => 'Lombardia',
            'phone' => '5678901234',
            'cachet' => '400',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut labore excepturi maiores enim molestias?'
        ],
        [
            'name' => 'Emma',
            'surname'=> 'Johnson',
            'email' => 'emma@example.com',
            'password' =>'emma567',
            'img' => 'https://example.com/images/emma.jpg',
            'region' => 'Basilicata',
            'phone' => '3456789123',
            'cachet' => '980',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum alias magnam saepe ipsa rem deleniti.'
        ],
        [
            'name' => 'Marco',
            'surname'=> 'Bianchi',
            'email' => 'mbianchi@example.com',
            'password' =>'marco987',
            'img' => 'https://example.com/images/marco.jpg',
            'region' => 'Veneto',
            'phone' => '6789012345',
            'cachet' => '350',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad modi numquam rem dolores, repellendus dignissimos!'
        ],
        [
            'name' => 'Sophia',
            'surname'=> 'Miller',
            'email' => 'sophia@example.com',
            'password' =>'sophia567',
            'img' => 'https://example.com/images/sophia.jpg',
            'region' => 'Umbria',
            'phone' => '4567890123',
            'cachet' => '150',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, distinctio architecto rem eum adipisci aut.'
        ],
        [
            'name' => 'Antonio',
            'surname'=> 'Ferrari',
            'email' => 'aferrari@example.com',
            'password' =>'antonio123',
            'img' => 'https://example.com/images/antonio.jpg',
            'region' => 'Emilia-Romagna',
            'phone' => '8901234567',
            'cachet' => '740',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit labore voluptatibus aperiam voluptate rerum enim!'
        ],
        [
            'name' => 'Isabella',
            'surname'=> 'Lee',
            'email' => 'isabella@example.com',
            'password' =>'isabella567',
            'img' => 'https://example.com/images/isabella.jpg',
            'region' => 'Abruzzo',
            'phone' => '6789123456',
            'cachet' => '680',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi, neque tempore ipsa repellat veritatis unde!'
        ],
        [
            'name' => 'Alessio',
            'surname'=> 'Martinez',
            'email' => 'amartinez@example.com',
            'password' =>'alessio123',
            'img' => 'https://example.com/images/alessio.jpg',
            'region' => 'Marche',
            'phone' => '7890123456',
            'cachet' => '310',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam aliquid incidunt voluptatem magnam cupiditate.'
        ],
        [
            'name' => 'Anastasia',
            'surname'=> 'Di Francesco',
            'email' => 'anafrance@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_d3d6707aab.jpeg',
            'region' => 'Lombardia',
            'phone' => '3342352009',
            'cachet' => '500',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Claudio',
            'surname'=> 'Niniano',
            'email' => 'claudio.niniano@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/cropped_resized_Claudio-Niniano-5866_a82c6_5Q1633O.jpeg',
            'region' => 'Lombardia',
            'phone' => '33923502001',
            'cachet' => '700',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Filippo',
            'surname'=> 'Hadu',
            'email' => 'djfili@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_60076cb0a9.jpeg',
            'region' => 'Lazio',
            'phone' => '3342352003',
            'cachet' => '270',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Fabio',
            'surname'=> 'Paglia',
            'email' => 'fabio.paglia@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_22f463562a.jpeg',
            'region' => 'Toscana',
            'phone' => '3342352002',
            'cachet' => '300',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Claudia',
            'surname'=> 'Rossi',
            'email' => 'claudia.rossi94@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_ebca13ca5b.jpeg',
            'region' => 'Lazio',
            'phone' => '3362342009',
            'cachet' => '300',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Erika',
            'surname'=> 'Mangiacotti',
            'email' => 'mangiacotti.erika@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_69af063777.jpeg',
            'region' => 'Sicilia',
            'phone' => '3382372301',
            'cachet' => '290',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Antonio',
            'surname'=> 'Procopio',
            'email' => 'proanto@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_d9d6b0bb16.jpeg',
            'region' => 'Calabria',
            'phone' => '336234900',
            'cachet' => '200',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Giorgio',
            'surname'=> 'Esposito',
            'email' => 'gesposito@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_1e78ce11a9.jpeg',
            'region' => 'Campania',
            'phone' => '3382345679',
            'cachet' => '400',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Liliya',
            'surname'=> 'Canargiu',
            'email' => 'lilicanargiu@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_36e2e13347.jpeg',
            'region' => 'Sardegna',
            'phone' => '3342372902',
            'cachet' => '250',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Andrea',
            'surname'=> 'Maurizio',
            'email' => 'andre.mauri@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/cropped_resized_Andrea-Maurizio-1710_2f1a1_qIYSc0N.jpeg',
            'region' => 'Veneto',
            'phone' => '3384567702',
            'cachet' => '230',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Amar',
            'surname'=> 'Corda',
            'email' => 'amarcorda838@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/cropped_resized_mariella-papanaga-7587_114a9_FQLY9li.jpeg',
            'region' => 'Lombardia',
            'phone' => '338456725',
            'cachet' => '150',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
            
        ],
        [
            'name' => 'Mariella',
            'surname'=> 'Papanaga',
            'email' => 'MPapanaga@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/cropped_resized_cantante-lirica-soprano-professionista-12863_FokLYge.jpeg',
            'region' => 'Campania',
            'phone' => '3884567789',
            'cachet' => '250',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
            
        ],
        [
            'name' => 'Gabry',
            'surname'=> 'Sax',
            'email' => 'saxgabri@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_928a9a69bf.jpeg',
            'region' => 'Calabria',
            'phone' => '3217567789',
            'cachet' => '350',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
            
        ],
        [
            'name' => 'Swingin',
            'surname'=> 'Cats',
            'email' => 'cats@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/cropped_resized_Raggi-Brillante-4et-22_1590e_cW5WKEz.jpeg',
            'region' => 'Emilia Romagna',
            'phone' => '3456412196',
            'cachet' => '500',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
            
        ],
        [
            'name' => 'Music',
            'surname'=> 'Live ',
            'email' => 'musiclive@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/cropped_resized_Estate-Live-Music-7478_b9c7f_lVyfsEI.jpeg',
            'region' => 'Veneto',
            'phone' => '3387631258',
            'cachet' => '425',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
            
        ],
        [
            'name' => 'Men on The',
            'surname'=> 'Moon',
            'email' => 'MenonThe@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_9697520c26.jpeg',
            'region' => 'Veneto',
            'phone' => '344196789',
            'cachet' => '390',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
            
        ],
        [
            'name' => 'ALFA',
            'surname'=> 'DJ',
            'email' => 'ALFA@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_427016c7cc.jpeg',
            'region' => 'Abruzzo',
            'phone' => '3384567789',
            'cachet' => '800',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
            
        ],
        [
            'name' => 'Swing Jazz',
            'surname'=> 'Trio',
            'email' => 'triojazz@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/cropped_resized_Swing-Jazz-Trio-5718_5e30d.jpeg',
            'region' => 'Emilia Romagna',
            'phone' => '33145697825',
            'cachet' => '200',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
            
        ],
        [
            'name' => 'Marco',
            'surname'=> 'Zorzi',
            'email' => 'marcozorzi8@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/cropped_resized_Marco-Pianist-6792_1d31c_CdEEgtj.jpeg',
            'region' => 'Veneto',
            'phone' => '34478912645',
            'cachet' => '850',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
            
        ],
        [
            'name' => 'Elisa',
            'surname' => 'Couto',
            'email' => 'coutoElisa@gmail.com',
            'password' => 'prova123',
            'img' => 'https://img.freepik.com/premium-photo/pianist-musician-piano-music-playing-musical-instrument-grand-piano-with-woman-performer_104603-2849.jpg',
            'region' => 'Liguria',
            'phone' => '3381426759',
            'cachet' => '320',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'La band',
            'surname'=> 'Pazza',
            'email' => 'laBandPazza@gmail.com',
            'password' => 'pazzissimi',
            'img' => 'https://media.istockphoto.com/id/496120274/it/foto/rock-band-esecuzione-in-uno-studio.jpg?s=612x612&w=0&k=20&c=RUH-ChyL6jEeJlUrpXzAWskINSJi0E0Vg_LiNw0Ur6E=',
            'region' => 'Campania',
            'phone' => '3383255485',
            'cachet' => '420',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Francesca',
            'surname'=> 'Romiti',
            'email' => 'Fromiti97@gmail.com',
            'password' => 'psw123',
            'img' => 'https://www.ondamusicale.it/wp-content/uploads/2020/08/bonnie-raitt.jpg',
            'region' => 'Emilia Romagna',
            'phone' => '3385744816',
            'cachet' => '150',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Giuseppina',
            'surname'=> 'Couto',
            'email' => 'GElisa@gmail.com',
            'password' => 'prova123',
            'img' => 'https://img.freepik.com/premium-photo/pianist-musician-piano-music-playing-musical-instrument-grand-piano-with-woman-performer_104603-2849.jpg',
            'region' => 'Liguria',
            'phone' => '5484521545',
            'cachet' => '320',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
    ];
    
?>