<?php

    return[
        
        [
            'name' => 'Giacomo',
            'surname'=> 'Paolini',
            'email' => 'gpaolini98@gmail.com',
            'password' => 'root',
            'img' => 'https://www.thomann.de/blog/wp-content/uploads/2017/01/10-conseils-pour-devenir-musicien-pro.jpg',
            'region' => 'Lazio',
            'phone' => '3384567789',
            'cachet' => '200',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Anastasia',
            'surname'=> 'Di Francesco',
            'email' => 'anafrance@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_d3d6707aab.jpeg',
            'region' => 'Lombardia',
            'phone' => '3342352009',
            'cachet' => '500',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Claudio',
            'surname'=> 'Niniano',
            'email' => 'claudio.niniano@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/cropped_resized_Claudio-Niniano-5866_a82c6_5Q1633O.jpeg',
            'region' => 'Lombardia',
            'phone' => '33923502001',
            'cachet' => '700',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Filippo',
            'surname'=> 'Hadu',
            'email' => 'djfili@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_60076cb0a9.jpeg',
            'region' => 'Lazio',
            'phone' => '3342352003',
            'cachet' => '270',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Fabio',
            'surname'=> 'Paglia',
            'email' => 'fabio.paglia@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_22f463562a.jpeg',
            'region' => 'Toscana',
            'phone' => '3342352002',
            'cachet' => '300',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Claudia',
            'surname'=> 'Rossi',
            'email' => 'claudia.rossi94@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_ebca13ca5b.jpeg',
            'region' => 'Lazio',
            'phone' => '3362342009',
            'cachet' => '300',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Erika',
            'surname'=> 'Mangiacotti',
            'email' => 'mangiacotti.erika@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_69af063777.jpeg',
            'region' => 'Sicilia',
            'phone' => '3382372301',
            'cachet' => '290',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Antonio',
            'surname'=> 'Procopio',
            'email' => 'proanto@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_d9d6b0bb16.jpeg',
            'region' => 'Calabria',
            'phone' => '336234900',
            'cachet' => '200',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Giorgio',
            'surname'=> 'Esposito',
            'email' => 'gesposito@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_1e78ce11a9.jpeg',
            'region' => 'Campania',
            'phone' => '3382345679',
            'cachet' => '400',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Liliya',
            'surname'=> 'Canargiu',
            'email' => 'lilicanargiu@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/project_thumb_36e2e13347.jpeg',
            'region' => 'Sardegna',
            'phone' => '3342372902',
            'cachet' => '250',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ],
        [
            'name' => 'Andrea',
            'surname'=> 'Maurizio',
            'email' => 'andre.mauri@gmail.com',
            'password' => 'root',
            'img' => 'https://www.musiqua.it/djmedia/cropped_main_band_pictures/cropped_resized_Andrea-Maurizio-1710_2f1a1_qIYSc0N.jpeg',
            'region' => 'Veneto',
            'phone' => '3384567702',
            'cachet' => '230',
            'experience' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus laboriosam, quae distinctio voluptas facere eaque totam rem libero quisquam architecto et non voluptatem cupiditate voluptates in id repudiandae vitae pariatur.',
        ]
    ]
?>